version: 1.0.{build}
build_script:
- cmd: >-
    call build_appveyor.cmd
    
artifacts:
- path: build\install

cache:
- "C:/projects/super-builder-libraries"
#- build\sources\ZLIB -> packages\zlib\CMakeLists.txt
#- build\sources\HDF5 -> packages\hdf5\CMakeLists.txt